export const fakeData = [
  { name: "John Doe", email: "john.doe@example.com", id: 1001 },
  { name: "Jane Smith", email: "jane.smith@example.com", id: 1002 },
  { name: "Alice Johnson", email: "alice.johnson@example.com", id: 1003 },
  { name: "Bob Williams", email: "bob.williams@example.com", id: 1004 },
  { name: "Eva Davis", email: "eva.davis@example.com", id: 1005 },
  { name: "Michael Brown", email: "michael.brown@example.com", id: 1006 },
  { name: "Olivia Taylor", email: "olivia.taylor@example.com", id: 1007 },
  { name: "Daniel Miller", email: "daniel.miller@example.com", id: 1008 },
  { name: "Sophia Wilson", email: "sophia.wilson@example.com", id: 1009 },
  { name: "Christopher Lee", email: "christopher.lee@example.com", id: 1010 },
  { name: "Emily Martinez", email: "emily.martinez@example.com", id: 1011 },
  {
    name: "William Anderson",
    email: "william.anderson@example.com",
    id: 1012,
  },
  { name: "Mia Thomas", email: "mia.thomas@example.com", id: 1013 },
  { name: "Matthew Garcia", email: "matthew.garcia@example.com", id: 1014 },
  { name: "Ava Robinson", email: "ava.robinson@example.com", id: 1015 },
  { name: "James Smith", email: "james.smith@example.com", id: 1016 },
  { name: "Emma Johnson", email: "emma.johnson@example.com", id: 1017 },
  { name: "Liam Davis", email: "liam.davis@example.com", id: 1018 },
  { name: "Isabella Harris", email: "isabella.harris@example.com", id: 1019 },
  { name: "Ryan Wilson", email: "ryan.wilson@example.com", id: 1020 },
  { name: "Abigail Moore", email: "abigail.moore@example.com", id: 1021 },
  { name: "Ethan Garcia", email: "ethan.garcia@example.com", id: 1022 },
  { name: "Ava Smith", email: "ava.smith@example.com", id: 1023 },
  { name: "Daniel Miller", email: "daniel.miller@example.com", id: 1024 },
  { name: "Sofia Davis", email: "sofia.davis@example.com", id: 1025 },
  { name: "Jackson Moore", email: "jackson.moore@example.com", id: 1026 },
  { name: "Olivia Taylor", email: "olivia.taylor@example.com", id: 1027 },
  { name: "Michael Brown", email: "michael.brown@example.com", id: 1028 },
  { name: "Chloe White", email: "chloe.white@example.com", id: 1029 },
  {
    name: "Alexander Harris",
    email: "alexander.harris@example.com",
    id: 1030,
  },
  { name: "Grace Robinson", email: "grace.robinson@example.com", id: 1031 },
  { name: "Lucas Thomas", email: "lucas.thomas@example.com", id: 1032 },
  { name: "Ella Anderson", email: "ella.anderson@example.com", id: 1033 },
  { name: "Carter Wilson", email: "carter.wilson@example.com", id: 1034 },
  {
    name: "Scarlett Johnson",
    email: "scarlett.johnson@example.com",
    id: 1035,
  },
  { name: "Henry Smith", email: "henry.smith@example.com", id: 1036 },
  { name: "Aria Davis", email: "aria.davis@example.com", id: 1037 },
  { name: "Mason Robinson", email: "mason.robinson@example.com", id: 1038 },
  { name: "Amelia Moore", email: "amelia.moore@example.com", id: 1039 },
  { name: "Liam Johnson", email: "liam.johnson@example.com", id: 1040 },
];
